"""add doctor profile template and watermark

Revision ID: 6a18e0dd9995
Revises: f94e75ff5aae
Create Date: 2026-07-08 18:32:58.929520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a18e0dd9995'
down_revision: Union[str, Sequence[str], None] = 'f94e75ff5aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_profiles', sa.Column('watermark_url', sa.String(length=500), nullable=True))
    op.add_column('doctor_profiles', sa.Column('template', sa.String(length=20), server_default='classic', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_profiles', 'template')
    op.drop_column('doctor_profiles', 'watermark_url')
    # ### end Alembic commands ###
